/*
===============================================================================
                           Dimensions and Dates Exploration
===============================================================================
*/

-- Retrieve a list of unique countries from which customers originate
SELECT DISTINCT country 
FROM gold.dim_customers
ORDER BY 1

-- Retrieve a list of unique categories, subcategories, and products
SELECT DISTINCT category, subcategory, product_name 
FROM gold.dim_products
ORDER BY 1,2,3

-- Determine the first and last order date and the total duration in months
SELECT MIN(order_date) AS first_order_date, MAX(order_date) AS last_order_date
, (EXTRACT(YEAR FROM AGE(MAX(order_date), MIN(order_date))) * 12) + EXTRACT(MONTH FROM AGE(MAX(order_date), MIN(order_date))) 
    AS order_range_months
FROM gold.fact_sales;

-- Find the youngest and oldest customer based on birthdate
SELECT
    MIN(birthdate) AS oldest_birthdate,
    EXTRACT(YEAR FROM AGE(CURRENT_DATE, MIN(birthdate))) AS oldest_age,
    MAX(birthdate) AS youngest_birthdate,
    EXTRACT(YEAR FROM AGE(CURRENT_DATE, MAX(birthdate))) AS youngest_age
FROM gold.dim_customers;


/*
===============================================================================
                       Measures Exploration (Key Metrics)
===============================================================================
*/

-- Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales

-- Find the Total number of Orders
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales

-- Find the total number of products
SELECT COUNT(product_name) AS total_products FROM gold.dim_products

-- Find the total number of customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers;

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales;

-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', round(AVG(price),4) FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', COUNT(customer_key) FROM gold.dim_customers;


/*
===============================================================================
                          Magnitude Analysis
===============================================================================
*/

-- Find total customers by countries
SELECT  country, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY 1
ORDER BY 2 DESC;

-- Find total customers by gender
SELECT gender, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY 1
ORDER BY 2 DESC;

-- Find total products by category
SELECT category, COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY 1
ORDER BY 2 DESC;

-- What is the average costs in each category?
SELECT category, AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY 1
ORDER BY 2 DESC;

-- What is the total revenue generated for each category?
SELECT p.category, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY 1
ORDER BY 2 DESC;


-- What is the total revenue generated by each customer?
SELECT c.customer_key, c.first_name, c.last_name
, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 1,2,3
ORDER BY 4 DESC;

-- What is the distribution of sold items across countries?
SELECT c.country, SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 1
ORDER BY 2 DESC;


/*
===============================================================================
                          Ranking Analysis
===============================================================================
*/
-- Which 5 products Generating the Highest Revenue?
-- Simple Ranking
SELECT p.product_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5


-- Complex but Flexibly Ranking Using Window Functions
SELECT *
FROM (
    SELECT
        p.product_name,
        SUM(f.sales_amount) AS total_revenue,
        RANK() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
        ON p.product_key = f.product_key
    GROUP BY 1
) AS ranked_products
WHERE rank_products <= 5;

-- What are the 5 worst-performing products in terms of sales?
SELECT p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY 1
ORDER BY 2
LIMIT 5

-- Find the top 10 customers who have generated the highest revenue
SELECT c.customer_key, c.first_name, c.last_name,
, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 1,2,3
ORDER BY 4 DESC
LIMIT 10


-- The 3 customers with the fewest orders placed
SELECT c.customer_key, c.first_name, c.last_name
, COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 1,2,3
ORDER BY 4 
LIMIT 3


